config/routes.rb
MonkeyDashboard::Application.routes.draw do
  namespace :accounting do
    resources :entries
  end

  get 'accounting', :controller => 'accounting', :action => 'overview'
  get 'accounting/balances/:account', :controller => 'accounting', :action => 'balances'
  get 'accounting/monthly-income', :controller => 'accounting', :action => 'monthly_income'
  get 'accounting/monthly-expenses', :controller => 'accounting', :action => 'monthly_expenses'
  get 'accounting/:action', :controller => 'accounting'

  get ':action', :controller => 'pages'

  root 'pages#home'

  

end

app/models/accounting.rb
module Accounting
end

app/models/accounting/entry.rb
require 'forwardable'

class Accounting::Entry
  include ActiveModel::Model
  extend Forwardable

  def_delegators :@entry, :date, :effective_date, :flag, :code, :description,
    :transactions, :amount, :null_amount, :id

  def self.ledger
    Monkey::Accounting.default_ledger
  end

  def self.all
    ledger.entries.map { |e| new e }
  end

  # Returns the entry identified by +param+ or +nil+.
  # @param param [String] entry ID as a string
  # @returns [Entry,nil] entry found or +nil+
  def self.find(param)
    all.detect { |e| e.to_param == param }
  end

  def self.count
    all.size
  end

  attr_reader :entry

  def initialize(entry_or_attributes = nil)
    if entry_or_attributes.nil?
      @entry = Monkey::Accounting::Entry.new(Date.today)
    elsif entry_or_attributes.is_a?(Monkey::Accounting::Entry)
      @entry = entry_or_attributes
    else
      date = entry_or_attributes[:date] || Date.today
      effective_date = entry_or_attributes[:effective_date]
      flag = entry_or_attributes[:flag]
      code = entry_or_attributes[:code]
      description = entry_or_attributes[:description]
      transactions = entry_or_attributes[:transactions] || []
      @entry = Monkey::Accounting::Entry.new(
        date, effective_date, flag, code, description, transactions)
    end
  end

  def destroy
    self.class.ledger.entries >> @entry
    self.class.ledger.save!
    true
  end

  def save
    self.class.ledger.entries << @entry
    self.class.ledger.save!
    true
  end

  def update(attributes = {})
    true
  end

  def persisted?
    !@entry.id.nil?
  end

  def to_param
    if persisted?
      @entry.id.to_s
    else
      nil
    end
  end
end

app/controllers/accounting/entries_controller.rb
class Accounting::EntriesController < ApplicationController
  before_action :set_accounting_entry, only: [:show, :edit, :update, :destroy]

  # GET /accounting/entries
  # GET /accounting/entries.json
  def index
    @accounting_entries = Accounting::Entry.all.sort_by(&:date)
  end

  # GET /accounting/entries/1
  # GET /accounting/entries/1.json
  def show
  end

  # GET /accounting/entries/new
  def new
    @accounting_entry = Accounting::Entry.new
  end

  # GET /accounting/entries/1/edit
  def edit
  end

  # POST /accounting/entries
  # POST /accounting/entries.json
  def create
    @accounting_entry = Accounting::Entry.new(accounting_entry_params)

    respond_to do |format|
      if @accounting_entry.save
        format.html { redirect_to @accounting_entry, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @accounting_entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @accounting_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounting/entries/1
  # PATCH/PUT /accounting/entries/1.json
  def update
    respond_to do |format|
      if @accounting_entry.update(accounting_entry_params)
        format.html { redirect_to @accounting_entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @accounting_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounting/entries/1
  # DELETE /accounting/entries/1.json
  def destroy
    @accounting_entry.destroy
    respond_to do |format|
      format.html { redirect_to accounting_entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accounting_entry
      @accounting_entry = Accounting::Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accounting_entry_params
      params[:accounting_entry]
    end
end

app/controllers/accounting_controller.rb
class AccountingController < ApplicationController
  def overview
    @entries = view_context.ledger.entries.sort_by(&:date)
    @first_date = @entries.first.date
    @last_date = @entries.last.date
  end

  def balances
    if params[:account]
      @account = view_context.ledger.account(params[:account])
      @accounts = @account.children
    else
      @account = nil
      @accounts = view_context.ledger.accounts.select { |a| a.parent.nil? }
    end
    @accounts.sort!
  end

  def monthly_income
    @monthly_income = monthly_summary(view_context.ledger.income_accounts)
  end

  def monthly_expenses
    @monthly_expenses = monthly_summary(view_context.ledger.expense_accounts)
  end

  private

  # Returns an array of [month_date, amount, average, avgdiff].
  def monthly_summary(accounts)
    last_entry = accounts.map(&:entries).flatten.sort_by(&:date).last
    @last_month = Date.parse(last_entry.date.prev_month.strftime('%Y-%m-01'))
    @first_month = @last_month.prev_year.next_month

    total = Monkey::Accounting::Amount.zero
    last_average = nil

    accounts.map(&:entries).flatten.select { |e|
      e.date >= @first_month and e.date < @last_month.next_month
    }.group_by { |e|
      e.date.strftime('%Y-%m-01')
    }.sort_by(&:first).map { |month_date_string, entries|
      month_date = Date.parse(month_date_string)
      amount = entries.map { |e| e.amount_to(accounts) }.reduce(:+)

      total += amount
      average = total / (distance_in_months(@first_month, month_date) + 1)
      avgdiff = last_average.nil? ? 0 : (average - last_average)
      last_average = average

      [month_date, amount, average, avgdiff]
    }
  end

  def distance_in_months(from_date, to_date)
    (to_date.year * 12 + to_date.month) -
      (from_date.year * 12 + from_date.month)
  end
end

app/helpers/accounting/entries_helper.rb
module Accounting::EntriesHelper
end

app/helpers/accounting_helper.rb
module AccountingHelper
end

app/views/accounting/entries/_form.html.erb
<%= form_for(@accounting_entry) do |f| %>
  <% if @accounting_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accounting_entry.errors.count, "error") %> prohibited this accounting_entry from being saved:</h2>

      <ul>
      <% @accounting_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table">
    <thead>
      <th>Date</th>
      <th>Description / Transactions</th>
      <th>Amount</th>
    </thead>
    <tbody>
      <tr>
        <td><%= f.date_field :date %></td>
        <td><%= f.text_field :description %></td>
        <td><%= f.text_field :amount %></td>
      </tr>
    </tbody>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounting/entries/edit.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Accounting', accounting_path %></li>
  <li><%= link_to 'Entries', accounting_entries_path %></li>
  <li><%= link_to @accounting_entry.id, @accounting_entry %></li>
  <li class="active">Edit</li>
</ol>

<%= render 'form' %>

app/views/accounting/entries/index.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Accounting', '/accounting' %></li>
  <li class="active">Entries</li>
  <li><%= link_to 'New', new_accounting_entry_path %></li>
</ol>

<table id="ledger" class="table table-hover">
  <thead>
    <th>Date</th>
    <th>Description / Transactions</th>
    <th class="text-right">Amount</th>
    <th>Actions</th>
  </thead>
  <tbody>
    <% @accounting_entries.each do |entry| %>
    <tr class="ledger-entry" entry-id="<%= entry.id %>">
      <td><%= entry.date %></td>
      <td><%= entry.description %></td>
      <td class="text-right"><%= raw(entry.amount.to_s.gsub(' ', '&nbsp;')) %></td>
      <td class="actions">
        <%= link_to '', entry, class: 'glyphicon glyphicon-new-window text-info' %>
        <%= link_to '', edit_accounting_entry_path(entry), class: 'glyphicon glyphicon-edit text-warning' %>
        <%= link_to '', entry, class: 'glyphicon glyphicon-remove text-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
    <% entry.transactions.each do |txn| %>
    <tr class="ledger-transaction" entry-id="<%= entry.id %>">
      <td></td>
      <td><%= txn.account %></td>
      <td class="text-right"><%= raw((txn.amount || entry.null_amount).to_s.gsub(' ', '&nbsp;')) %></td>
      <td></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/accounting/entries/new.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Accounting', accounting_path %></li>
  <li><%= link_to 'Entries', accounting_entries_path %></li>
  <li class="active">New</li>
</ol>

<%= render 'form' %>

app/views/accounting/entries/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Accounting', accounting_path %></li>
  <li><%= link_to 'Entries', accounting_entries_path %></li>
  <li class="active"><%= @accounting_entry.id %></li>
  <li><%= link_to 'Edit', edit_accounting_entry_path(@accounting_entry) %></li>
</ol>

<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <th>Date</th>
    <th>Description / Transactions</th>
    <th>Amount</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @accounting_entry.date %></td>
      <td><%= @accounting_entry.description %></td>
      <td><%= @accounting_entry.amount %></td>
    </tr>
  </tbody>
</table>